# Generated by Django 4.2.9 on 2024-09-08 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_client', models.CharField(max_length=50)),
                ('nom_du_modele', models.CharField(max_length=50)),
                ('vos_mesures', models.TextField(max_length=100)),
                ('date_commande', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_contenu', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('comment_faire', models.FileField(blank=True, null=True, upload_to='blog_videos')),
                ('par_le_couturier', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('tissu_adapte', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='couturier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=30)),
                ('nom_populaire', models.CharField(max_length=30)),
                ('contact', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30)),
                ('nom_atelier', models.CharField(max_length=30)),
                ('adresse_atelier', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog_images')),
            ],
        ),
        migrations.CreateModel(
            name='demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_couturier', models.CharField(max_length=100)),
                ('nom_du_contenu', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MaisonCouture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('photo_atel', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('telephone', models.CharField(max_length=15)),
                ('specialisation', models.CharField(choices=[('CoutureHomme', 'Couturehomme'), ('CoutureFemme', 'Couturefemme'), ('CoutureMixte', 'Couturemixte')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('site_web', models.URLField()),
                ('description', models.TextField()),
                ('date_creation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_du_modele', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('nom_modele', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('couturier', models.CharField(max_length=50)),
                ('mesures_a_prendre', models.TextField(max_length=100)),
                ('tissus_possible', models.TextField(max_length=100)),
                ('quantite_necessaire_de_tissus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('nomode', models.CharField(max_length=30)),
                ('topic', models.CharField(choices=[('Tendance', 'Tendance'), ('Culturel', 'Culturel'), ('Hautecouture', 'Hautecouture')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('explain', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('pub_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_visite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ajouter_commentaire', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patron')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
