# Generated by Django 4.2.9 on 2024-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couturier',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
    ]
